### PR TITLE
Bug 528403 - Architecture Management Resource not compliant to AM 2.0

### PR DESCRIPTION
**Pull request by berezovskyi**
Change `serviceProvider: URI` to `serviceProvider: Set<URI>`

### CODE REVIEW

**Comment by berezovskyi** [comment]
https://git.eclipse.org/r/#/c/122641/

**Comment by berezovskyi** [comment]
I don't know what's causing the merge conflict

**Comment by jamsden** [comment]
Hummm.... There are two ArchitectureResources, one in oslc-java-client, and another in oslc4j-client, both having the same package. Could that be it?

**Comment by berezovskyi** [comment]
Hmm maybe, but please see #35 because I can't tell them apart.

**Comment by jamsden** [comment]
I probably need to rename the packages in oslc4j-client. Do you have a suggestion?

**Comment by berezovskyi** [comment]
Jim, sorry I was wrong. Yes both modules have the classes with the same package name. Solution: never use both of them together in one project, either A or B.

This conflict cannot cause use merge conflicts for Git.

**Comment by berezovskyi** [comment]
@benjaminr-ps sorry for a delay in handling your PR. Could you please update it to target https://github.com/eclipse/lyo.client/blob/master/oslc-java-client/src/main/java/org/eclipse/lyo/client/oslc/resources/ArchitectureResource.java if it's still relevant for you?

**Comment by benjaminr-ps** [comment]
The ArchitectureResource class you are referring to is still missing the correct cardinality for service providers.

But, looking to the lyo.domains respository, it is correctly defined. (https://github.com/eclipse/lyo.domains/blob/master/oslc-domains/src/main/java/org/eclipse/lyo/oslc/domains/am/Resource.java)

In the [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=528403) Jad pointed to lyo.domains repository as single source of truth.

**Comment by berezovskyi** [comment]
#106 will deprecate the class; wontfix - use lyo.domains

**Pull request closed without merging**
