### PR TITLE
Deleting the sample code that is now located under https://github.com/OSLC/lyo-samples/

### PR DESCRIPTION
**Pull request by jadelkhoury**
2 issues remain:
1. The readme states that oauth-test has also moved. But I could not locate that code under https://github.com/OSLC/lyo-samples/.
1. Why is oslc4j-client-samples not migrated?

### CODE REVIEW

**Comment by berezovskyi** [comment]
Now regarding your questions.

OAuth related code is under https://github.com/OSLC/lyo-samples/blob/master/oauth-cli-helper/src/main/java/org/eclipse/lyo/client/oauth/sample/OAuthClient.java I have no idea why the `artifactId` is not the same, I tried to ensure I only rename folders not IDs.

`oslc4j-client-samples` are not migrated because this is a "new" repo that @jamsden created to have a set of matching samples for the new version of the Lyo Client. We might also want to move it to the samples repo outside Lyo, but that's up to you and @jamsden.

**Comment by jadelkhoury** [comment]
Ok. I thought this was a simple delete I thought I can help with. But if the code has diverged, I'd rather someone else that was involved (you? @jamsden) take care of it.

**Comment by berezovskyi** [comment]
Sure. But thanks for getting the process going, Jad!

--
/Andrew
(from phone)



On Mon, Apr 8, 2019 at 10:52 PM +0200, "Jad El-khoury" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok. I thought this was a simple delete I thought I can help with. But if the code has diverged, I'd rather someone else that was involved (you? @jamsden<https://github.com/jamsden>) take care of it.

**Comment by berezovskyi** [comment]
Submitted new PRs

**Pull request closed without merging**
