### PR TITLE
Force httpclient version

### LINKED ISSUE #85: json-ld support fails if server also includes the OSLC client library
I have an adaptor that also includes the latest oslc-client library `oslc4j-client` (the one for jax-rs 2.0).

If I do a GET JSON-LD, I will get the exception below! 
Why? As soon as I include the `oslc4j-client` library, I end up using the Apache httpclient version 4.0 (due to the old oauth library). Without `oslc4j-client`, I use the needed httpclient version 4.5.10.

### Dependency Hierarchy for an adaptor without `oslc4j-client`
withoutOSLCClient

### Dependency Hierarchy for an adaptor with `oslc4j-client`
withOSLCClient

### Exception
```
javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: org/apache/http/client/RedirectStrategy
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:168)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
```

### PR DESCRIPTION
**Pull request by jadelkhoury**
Fixes #85

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@berezovskyi I'm no maven expert, but is this good enough. But I'm learning :-)

**Comment by jadelkhoury** [comment]
I have tested this change in 2 ways:

1. adaptor-rm sample adaptor now works for json-ld
2. client-oauth-discovery-dui (from https://github.com/OSLC/lyo-samples/tree/master/client-oauth-discovery-dui) also worked very fine. This means using the latter version of httpclient does not affect oauth library negatively.

**Comment by berezovskyi** [comment]
Though I am not sure how did the problem begin in the first place. I used a dependencyManagement mechanism to force the version: https://stackoverflow.com/a/9119183/464590

Maybe you don't even need to add the client library and just to update the version?

**Comment by jadelkhoury** [comment]
dependencyManagement already has a dependency on 4.5.6, and that did not help.
https://github.com/eclipse/lyo.client/blob/4a7e994b4ede142e203be44ef7aa514b561ed9aa/oslc4j-client/pom.xml#L143

Since I am sure you will have input on the next fix I make, can we make sure I understand what you mean with the exclusion suggestion? that is:
from
```
<dependency>
            <groupId>net.oauth.core</groupId>
            <artifactId>oauth-httpclient4</artifactId>
            <version>20090913</version>
</dependency>
```

to this?

```
<dependency>
            <groupId>net.oauth.core</groupId>
            <artifactId>oauth-httpclient4</artifactId>
            <version>20090913</version>
           <exclusions>
             <exclusion>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpclient</artifactId>
              </exclusion>
        </exclusions>
</dependency>

```

**Comment by jadelkhoury** [comment]
@berezovskyi  please review this last change. thanks.

**Pull request merged**
