### PR TITLE
Refactor the clients

### LINKED ISSUE #106: Rename oslc4j-client to lyo-client and refactor
Rationale: we are trying to have all projects be named lyo-xyz and drop OSLC4J. I am also constantly confused with which of them is new and which is old.

---

**Action plan**

- [x] make a 4.0.0.M2 release before that to provide a temporary but reliable workaround for all the SNAPSHOT code out there
- [x] `oslc-java-client` stays with the same name, package namespace (`org.eclipse.lyo.client.oslc`), and a bumped version 4.0 but with all classes under `client.oslc` and `client.jazz` deprecated.
- [x] `oslc4j-client` is renamed to `oslc-client` and `org.eclipse.lyo.oslc4j.client` code is moved to `org.eclipse.lyo.client`. Note that `oslc` is missing at the end and this is how we avoid clashes technically. ~~Also, classes are renamed from `OslcClientXYZ` to `LyoClientXYZ`; this is how we signal to developers which classes to use.~~ dropped because of disagreement over the package name
- [x] `client.exception` and `client.resources` are moved into two differnt packages (read below why) and previously discussed deprecations are made to `client.resources` because `lyo-domains` is preferred. NB! Check the steps taken in https://github.com/eclipse/lyo.domains/pull/20
- [x] `oslc-java-client` depends on `oslc-client-base` (where I will move `client.exception` code) and `oslc-java-client-resources` (where `client.resources` will go). However, `lyo-client` will only depend on `lyo-client-base` and users will be advised to depend on `lyo-domains` BUT they will be able to also load `oslc-java-client-resources` if really needed.

### PR DESCRIPTION
**Pull request by berezovskyi**
Closes #106

### CODE REVIEW

**Comment by berezovskyi** [comment]
@jadelkhoury @jamsden I have done the refactoring with 2 minor changes from the plan agreed on in #106:

- I did not rename new OslcClient to LyoClient because we agreed to name the project oslc-client instead of lyo-client
- Query-related classes were inside the .resources package but they were modified in the new client, so I left them "duplicated"

**Comment by berezovskyi** [comment]
It will be easiest for you not to review the diff but instead:

- see how the overall result looks like in https://github.com/eclipse/lyo.client/tree/0de7cea0195ee73af9d21b531a5d8b6746b4f752
- see what did I do in individual commits https://github.com/eclipse/lyo.client/pull/110/commits

**Review by jamsden — APPROVED** [review]
I didn't go through each change, but this generally looks right to me.

**Comment by berezovskyi** [comment]
I have merged this so that it can get pubished as snapshot as soon as possible and we can look for any bugs.

@jadelkhoury tell me if any of your client usages break, mostly you should have to:

1) Change the artifactId - @jadelkhoury @jamsden this reminds me that we forgot to overwrite oslc4j-client somehow - either to remove all classes from SNAPSHOT or mark all of them `@Deprecated`, so for now your code most likely won't break, you should actively change the artifactId to test it.
2) Remove `oslc4j` from the package name on the imports.
3) Replace `resources` with `query` in the package name of the Query-related imports.

**Pull request merged**
