### PR TITLE
Adding support for managing or obtaining the catalogUrl for Configuration Management service provider catalog

### PR DESCRIPTION
**Pull request by isccarrasco**
Adding support for getting the catalogUrl for the Configuration Management.

### CODE REVIEW

**Comment by berezovskyi** [comment]
I merged the https://github.com/eclipse/lyo.client/pull/69 but I still see the changes from it. Could you please merge master into this branch, please?

**Comment by berezovskyi** [comment]
You also need to sign an ECA (an Eclipse account is needed for that).

**Comment by isccarrasco** [comment]
I already have the ECA, but I guess I need to modify the previous commits to sign them.

**Comment by berezovskyi** [comment]
Congrats on your first contribution to Lyo!

**Pull request merged**
