### PR TITLE
Clean up Lyo Client after moving DS to Domains

### PR DESCRIPTION
**Pull request by berezovskyi**
Changes:

- remove resource classes (moved to https://github.com/eclipse/lyo.domains/pull/20)
- remove old client, version 2.4.0 should be used if it is needed.
- some people buiding integration tools may need to use old client to talk to old OSLCv1 tools and the new client to talk to the OSLCv2 and v3 tools. For this reason, following the advice in https://github.com/EsotericSoftware/kryo/issues/650, I moved the new client under `org.eclipse.lyo.client.v4`. In the future, this will allow using Lyo 2.4, 4.0, 5.0 etc clients in the same project (* that is not at the same time an OSLC Server), increasing the ability to build versatile integration solutions. Also, we should stop using OSLC4J term altogether, every use of OSLC4J shall be replaced with Lyo.
- rename artefact to `org.eclipse.lyo.clients:lyo-client-v4` for the same reason as above. This will allow adding multiple clients into the same project if the integration needs require different Lyo Clients to be used against different OSLC endpoints.
- move `resources.RmUtil` to `util.RmUtil`
- move JEE class under `jazz` package.

### CODE REVIEW

**Comment by berezovskyi** [comment]
The build shall succeed once https://github.com/eclipse/lyo.domains/pull/20 is merged.

**Comment by berezovskyi** [comment]
Scratch that. After a good night of sleep, I understood that I am just pushing the diamond dependency further down.

**Comment by jadelkhoury** [comment]
You're closing this request then?

**Comment by berezovskyi** [comment]
No, I am going back to the idea that only OSGi can allow proper use of multiple Lyo client versions in the same program. I will revert the package and artifact name changes back. There will be no 'old' client on 4.0 branch any more, all old users will have to keep using 2.4 client. I will try to change the new client so that the migration effort from 2.4 to 4.0 is minimal beyond the POM change.

The reason behind -4 in the name was to enable using 2.4, 4.0, 5.0 etc clients all together in the same project in the future if needed. I am only reverting because my approach won't work, not because such property is not highly desirable.

--
Best regards,
Andrew

On 27 April 2020, at 11:48, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:



You're closing this request then?

**Pull request closed without merging**
